services:

  app:
    container_name: note-creation-app
    image: note-creation-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/note_creation_db
        SPRING_DATASOURCE_USERNAME: user_note_creation
        SPRING_DATASOURCE_PASSWORD: 123456789
    networks:
      - spring-demo
    depends_on:
      - postgres
      - mail-dev
    restart: always
  mail-dev:
    container_name: note-creation-maildev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  postgres:
    container_name: note-creation-db
    image: postgres
    environment:
      POSTGRES_USER: user_note_creation
      POSTGRES_PASSWORD: 123456789
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: note_creation_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: always

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
